/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_matias_ndkfractalviewer_FractalLibJNIWrapper */

#ifndef _Included_com_example_matias_ndkfractalviewer_FractalLibJNIWrapper
#define _Included_com_example_matias_ndkfractalviewer_FractalLibJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_matias_ndkfractalviewer_FractalLibJNIWrapper
 * Method:    on_surface_created
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_matias_ndkfractalviewer_FractalLibJNIWrapper_on_1surface_1created
  (JNIEnv *, jclass);

/*
 * Class:     com_example_matias_ndkfractalviewer_FractalLibJNIWrapper
 * Method:    on_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_matias_ndkfractalviewer_FractalLibJNIWrapper_on_1surface_1changed
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_matias_ndkfractalviewer_FractalLibJNIWrapper
 * Method:    on_draw_frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_matias_ndkfractalviewer_FractalLibJNIWrapper_on_1draw_1frame
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
